[package]
name = "wgpu-poc"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = { version = "0.30.12" }
wgpu = { version = "26.0" }
pollster = { version = "0.4.0" }
image = { version = "0.25.6" }
bincode = { version = "2.0.1" }
